spring:
  profiles:
    active: test
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:8889/dealer
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
security:
  jwt:
    secret-key: fcf06d5552acc5c6488a45e740428d5c0ab05377834fc76257dd8cf8e470dcf1
    expiration-time: 3600000000